=== wiinuk/vscode-lua/server/src/server/resources.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="resources">
    <xsd:complexType>
      <xsd:all>
        <xsd:element name="diagnostic-messages" type="diagnostic-messages" />
        <xsd:element name="log-messages" type="log-messages" />
      </xsd:all>
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="diagnostic-messages">
    <xsd:all>
      <xsd:element name="RequireFieldSep" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireToken" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireBinaryOp" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireUnaryOp" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireLiteral" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireName" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireString" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireVar" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="DisallowedLeadingNewLine" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireAnyStat" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireAnyField" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireAnyFieldKey" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireAnyTypeSign" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireNameOrDot3" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireAssignStatOrFunctionCall" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireEndOfSource" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireNameOrLBracket" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="TypeMismatch" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>string -&gt; string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireField" type="pattern-4">
        <xsd:annotation>
          <xsd:documentation>actualFields: string -&gt; requireKey: string -&gt; requireType: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="UndefinedField" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>selfType: string -&gt; fieldKey: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="KindMismatch" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>string -&gt; string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ConstraintMismatch" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>string -&gt; string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ConstraintAndTypeMismatch" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>string -&gt; string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="TagSpaceConstraintMismatch" type="pattern-5">
        <xsd:annotation>
          <xsd:documentation>expectedLowerBound: string -&gt; expectedUpperBound: string -&gt; actualType: string -&gt; requireElement: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ParseError" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="UnifyError" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ReturnValueIgnored" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="NameNotFound" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="IndirectGlobalRequireUse" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ModuleNotFound" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>moduleName: string -&gt; searchedModulePaths: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ExternalModuleError" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>modulePath: string -&gt; diagnostic: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RecursiveModuleReference" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>modulePath: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="UnrecognizableGlobalPackageUse" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="TypeNameNotFound" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="TypeArityMismatch" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>expectedArity: int -&gt; actualArity: int -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="DuplicateFieldKey" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>string -&gt; otherFieldSpan: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RedeclarationOfSpecialGlobalVariable" type="pattern-4">
        <xsd:annotation>
          <xsd:documentation>name: string -&gt; oldKind: string -&gt; newKind: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RedeclarationOfBasicType" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RedeclarationOfTypeVariable" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>name: string -&gt; oldTypeLocations: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="UndeterminedGlobalVariableEnvironment" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>modulePath: string -&gt; additionalGlobals: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="GlobalNameCollision" type="pattern-5">
        <xsd:annotation>
          <xsd:documentation>name: string -&gt; decl1: string -&gt; decl2: string -&gt; decls: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="GlobalTypeCollision" type="pattern-5">
        <xsd:annotation>
          <xsd:documentation>name: string -&gt; type1: string -&gt; type2: string -&gt; types: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="UnrecognizedFeatureName" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>featureName: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="UnexpectedMultiType" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequireMultiType" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="DuplicateTag" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>otherTagName: string -&gt; otherTagSpan: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="FieldParentTagNotFound" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="GenericTagParentSyntaxNotFound" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="TypeTagParentSyntaxNotFound" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="Info" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="Warning" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="Error" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="NoFeatures" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="GlobalRequire" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="GlobalPackage" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="GenericTypeParameters" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="GenericTypeSubstitute" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>typeParameterName: string -&gt; typeName: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="OtherFieldLocation" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="OtherTagLocation" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:all>
  </xsd:complexType>
  <xsd:complexType name="log-messages">
    <xsd:all>
      <xsd:element name="LoadResourceFrom" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>resourcePath: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ServerStarting" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ServerTerminatedNormally" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="RequestCanceled" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>requestId: int -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="MessageParseError" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>error: ErrorKind -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ReceivedExitNotification" type="pattern-1">
        <xsd:annotation>
          <xsd:documentation>string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="MessageReceived" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>message: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="UnknownRequest" type="pattern-4">
        <xsd:annotation>
          <xsd:documentation>requestId: int -&gt; method: Methods -&gt; params: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="UnknownNotification" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>method: Methods -&gt; params: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="InvalidMessageFormat" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>message: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ErrorResponseReceived" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>error: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ResponseHandlerNotFound" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>id: int -&gt; result: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="ResourceValidationError" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>message: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="MessageSending" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>json: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="BeginCheck" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>filePath: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="EndCheck" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>milliSeconds: Double -&gt; filePath: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="UnopenedFileDiagnosticsIsNotPublished" type="pattern-2">
        <xsd:annotation>
          <xsd:documentation>filePath: string -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="FileChanged" type="pattern-3">
        <xsd:annotation>
          <xsd:documentation>path: string -&gt; changeType: FileChangeType -&gt; string</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
    </xsd:all>
  </xsd:complexType>
  <xsd:simpleType name="pattern-1">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([^{}]|\{\{|\}\})*" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="pattern-5">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([^{}]|\{\{|\}\})*(\{[0123]\}([^{}]|\{\{|\}\})*)*" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="pattern-4">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([^{}]|\{\{|\}\})*(\{[012]\}([^{}]|\{\{|\}\})*)*" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="pattern-3">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([^{}]|\{\{|\}\})*(\{[01]\}([^{}]|\{\{|\}\})*)*" />
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:simpleType name="pattern-2">
    <xsd:restriction base="xsd:string">
      <xsd:pattern value="([^{}]|\{\{|\}\})*(\{[0]\}([^{}]|\{\{|\}\})*)*" />
    </xsd:restriction>
  </xsd:simpleType>
</xsd:schema>

=== wiinuk/vscode-lua/server/src/server/resources.ja-jp.xml
<?xml version="1.0" encoding="utf-8" ?>
<resources xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="resources.xsd">
  <diagnostic-messages>
    <RequireField>フィールド `{1}` ( 型 `{2}` ) が見つかりませんでした。見つかったフィールド `{0}`</RequireField>
    <UndefinedField>型 `{0}` にフィールド `{1}` が見つかりませんでした</UndefinedField>
    <TypeMismatch>型 `{0}` と `{1}` が一致しません</TypeMismatch>
    <UnifyError>一般的な型エラー：{0}</UnifyError>
    <NameNotFound>`{0}` が見つかりませんでした</NameNotFound>
    <ReturnValueIgnored>戻り値が無視されました</ReturnValueIgnored>
    <ModuleNotFound>モジュール `{0}` が見つかりませんでした。&#x0A;探した場所：&#x0A;{1}</ModuleNotFound>
    <IndirectGlobalRequireUse>モジュール名を解析できません。`require("&lt;モジュール名&gt;")` のような形式なら解析できます</IndirectGlobalRequireUse>
    <ExternalModuleError>他のモジュールで問題が見つかりました：{0}&#x0A;内容：{1}</ExternalModuleError>
    <RecursiveModuleReference>モジュールが自分自身を参照しています：{0}</RecursiveModuleReference>
    <ConstraintMismatch>制約 `{0}` と `{1}` が一致しませんでした</ConstraintMismatch>
    <KindMismatch>種類 `{0}` と `{1}` が一致しませんでした</KindMismatch>
    <ConstraintAndTypeMismatch>制約 `{0}` が必要です。型 `{1}` は制約を満たしませんでした</ConstraintAndTypeMismatch>
    <UnrecognizableGlobalPackageUse>パッケージのパスを解析できません。`package.path = package.path .. ";&lt;パス&gt;"` のような形式なら解析できます</UnrecognizableGlobalPackageUse>
    <TypeNameNotFound>型 `{0}` が見つかりませんでした。型変数を指定したいときは、1文字の名前か'T'から始まる名前 ( `a`、`V`、`TResult`、`TElement` など ) を使ってください</TypeNameNotFound>
    <TypeArityMismatch>{0}個の型引数が必要です。3個の型引数は `Type&lt;_, _, _&gt;` のように指定します。0個の型引数は `Type` のように指定します。今の型引数は {1} 個です</TypeArityMismatch>
    <DuplicateFieldKey>フィールド `{0}` が重複しています</DuplicateFieldKey>
    <RedeclarationOfSpecialGlobalVariable>前からあった `{0}` ( {1} ) は隠されました。`{0}` の扱いは `{2}` に変更されます</RedeclarationOfSpecialGlobalVariable>
    <RedeclarationOfBasicType>基本型 `{0}` は再宣言できません</RedeclarationOfBasicType>
    <RedeclarationOfTypeVariable>型変数 `{0}` は再宣言できません</RedeclarationOfTypeVariable>
    <UndeterminedGlobalVariableEnvironment>この場所で `require` を使うとグローバル環境が不確定になります。可能なら `require` をソースの一番上に移すことを検討してください。&#x0A;モジュール：&#x0A;{0}&#x0A;モジュールによって追加されるグローバル変数：&#x0A;{1}</UndeterminedGlobalVariableEnvironment>
    <GlobalNameCollision>`{0}` の複数のグローバル宣言が一致しませんでした：&#x0A;{1}&#x0A;{2}{3}</GlobalNameCollision>
    <GlobalTypeCollision>`{0}` の複数の型定義が一致しませんでした：&#x0A;{1}&#x0A;{2}{3}</GlobalTypeCollision>
    <UnrecognizedFeatureName>特徴 `{0}` は認識できません</UnrecognizedFeatureName>
    <UnexpectedMultiType>ここに複型を指定することはできません</UnexpectedMultiType>
    <RequireMultiType>複型が必要です。`()` や `(number,)` や `(number, string, ...)` や `...` などが有効です</RequireMultiType>
    <DuplicateTag>タグ `{0}` が重複しています</DuplicateTag>
    <FieldParentTagNotFound>親タグ ( `@class` など ) がこのタグの前に必要です。このタグは無視されます</FieldParentTagNotFound>
    <UnificationStackTooDeep>型推論の深さが上限に達しました。型注釈をつけると解決する場合があります</UnificationStackTooDeep>

    <Error>エラー</Error>
    <Warning>警告</Warning>
    <Info>情報</Info>

    <NoFeatures>通常の変数</NoFeatures>
    <GlobalRequire>モジュールの解決</GlobalRequire>
    <GlobalPackage>解決パスの追加</GlobalPackage>

    <GenericTypeParameters>ジェネリックパラメーター</GenericTypeParameters>
    <GenericTypeSubstitute>{0} は {1}</GenericTypeSubstitute>
    <OtherFieldLocation>他のフィールドの場所</OtherFieldLocation>
    <OtherTagLocation>他のタグの場所</OtherTagLocation>
    <TypeSource>型の推論元</TypeSource>
    <ConstraintsSource>制約の推論元</ConstraintsSource>
    <Type1Source>型1の推論元</Type1Source>
    <Type2Source>型2の推論元</Type2Source>
    <Constraints1Source>制約1の推論元</Constraints1Source>
    <Constraints2Source>制約2の推論元</Constraints2Source>
    <ActualTypeSource>実際の型の推論元</ActualTypeSource>
    <RequiresTypeSource>必要な型の推論元</RequiresTypeSource>

    <ParseError>一般的な構文エラー：{0}</ParseError>
    <DisallowedLeadingNewLine>トークンの前の改行は無効です</DisallowedLeadingNewLine>
    <RequireAnyField>フィールドが必要です</RequireAnyField>
    <RequireAnyStat>式が必要です</RequireAnyStat>
    <RequireBinaryOp>`+`、`*` などの二項演算子が必要です</RequireBinaryOp>
    <RequireUnaryOp>`-`、`#` などの単項演算子が必要です</RequireUnaryOp>
    <RequireLiteral>`true`、`false`、`nil`、数値、文字列などの即値が必要です</RequireLiteral>
    <RequireName>名前が必要です</RequireName>
    <RequireString>文字列が必要です</RequireString>
    <RequireToken>`{0}` が必要です</RequireToken>
    <RequireFieldSep>`,`、`;` などのフィールド区切りが必要です</RequireFieldSep>
    <RequireVar>名前や `x.f`、`x[n]` などの変数式が必要です</RequireVar>
    <RequireAnyFieldKey>フィールドのキーが必要です。 例：`key`、`"key"`、`123`、`true`</RequireAnyFieldKey>
    <RequireAnyTypeSign>型が必要です。例：`string`、`table&lt;number, a&gt;`、`{{ x: _, y: any }}`、`TElement[]`</RequireAnyTypeSign>
    <RequireAssignStatOrFunctionCall>`x = 10` などの代入文または `f(10)` などの関数呼び出し文が必要です</RequireAssignStatOrFunctionCall>
    <RequireEndOfSource>ソースの終わりが必要です</RequireEndOfSource>
    <RequireNameOrDot3>名前か `...` が必要です</RequireNameOrDot3>
    <RequireNameOrLBracket>名前か `(` が必要です</RequireNameOrLBracket>
  </diagnostic-messages>

  <log-messages>
    <LoadResourceFrom>リソースを読み込みました。場所：{0}</LoadResourceFrom>
    <ServerStarting>サーバーを開始しています</ServerStarting>
    <ServerTerminatedNormally>サーバーが正常に終了しました</ServerTerminatedNormally>
    <UnknownRequest>不明な要求を受信しました[{0}] {1} `{2}`</UnknownRequest>
    <MessageReceived>メッセージを受信：{0}</MessageReceived>
    <MessageParseError>メッセージ解析エラー</MessageParseError>
    <ReceivedExitNotification>`exit` 通知を受信しました</ReceivedExitNotification>
    <RequestCanceled>要求 {0} がキャンセルされました</RequestCanceled>
    <UnknownNotification>不明な通知 {0}：{1}</UnknownNotification>
    <InvalidMessageFormat>メッセージの形式が無効です：{0}</InvalidMessageFormat>
    <ErrorResponseReceived>エラーを受信：{0}</ErrorResponseReceived>
    <ResponseHandlerNotFound>応答ハンドラーが見つかりません。ID：{0}、返答：{1}</ResponseHandlerNotFound>
    <ResourceValidationError>リソースの検証に失敗しました：{0}</ResourceValidationError>
    <MessageSending>返信：{0}</MessageSending>
    <BeginCheck>解析中 {0}</BeginCheck>
    <EndCheck>解析完了 {0}ミリ秒、{1}</EndCheck>
    <UnopenedFileDiagnosticsIsNotPublished>開いていないファイルの診断結果は公開されません：{0}</UnopenedFileDiagnosticsIsNotPublished>
    <FileChanged>ファイルの変更を検知しました：{0}、{1}</FileChanged>
  </log-messages>

</resources>

=== wiinuk/vscode-lua/server/src/server/resources.xml
<?xml version="1.0" encoding="utf-8"?>
<resources p1:noNamespaceSchemaLocation="resources.xsd" xmlns:p1="http://www.w3.org/2001/XMLSchema-instance">
  <diagnostic-messages>
    <RequireFieldSep>RequireFieldSep</RequireFieldSep>
    <RequireToken>RequireToken({0})</RequireToken>
    <RequireBinaryOp>RequireBinaryOp</RequireBinaryOp>
    <RequireUnaryOp>RequireUnaryOp</RequireUnaryOp>
    <RequireLiteral>RequireLiteral</RequireLiteral>
    <RequireName>RequireName</RequireName>
    <RequireString>RequireString</RequireString>
    <RequireVar>RequireVar</RequireVar>
    <DisallowedLeadingNewLine>DisallowedLeadingNewLine</DisallowedLeadingNewLine>
    <RequireAnyStat>RequireAnyStat</RequireAnyStat>
    <RequireAnyField>RequireAnyField</RequireAnyField>
    <RequireAnyFieldKey>RequireAnyFieldKey</RequireAnyFieldKey>
    <RequireAnyTypeSign>RequireAnyTypeSign</RequireAnyTypeSign>
    <RequireNameOrDot3>RequireNameOrDot3</RequireNameOrDot3>
    <RequireAssignStatOrFunctionCall>RequireAssignStatOrFunctionCall</RequireAssignStatOrFunctionCall>
    <RequireEndOfSource>RequireEndOfSource</RequireEndOfSource>
    <RequireNameOrLBracket>RequireNameOrLBracket</RequireNameOrLBracket>
    <TypeMismatch>TypeMismatch({0}, {1})</TypeMismatch>
    <RequireField>RequireField({0}, {1}, {2})</RequireField>
    <UndefinedField>UndefinedField({0}, {1})</UndefinedField>
    <KindMismatch>KindMismatch({0}, {1})</KindMismatch>
    <ConstraintMismatch>ConstraintMismatch({0}, {1})</ConstraintMismatch>
    <ConstraintAndTypeMismatch>ConstraintAndTypeMismatch({0}, {1})</ConstraintAndTypeMismatch>
    <TagSpaceConstraintMismatch>TagSpaceConstraintMismatch({0}, {1}, {2}, {3})</TagSpaceConstraintMismatch>
    <ParseError>ParseError({0})</ParseError>
    <UnifyError>UnifyError({0})</UnifyError>
    <ReturnValueIgnored>ReturnValueIgnored</ReturnValueIgnored>
    <NameNotFound>NameNotFound({0})</NameNotFound>
    <IndirectGlobalRequireUse>IndirectGlobalRequireUse</IndirectGlobalRequireUse>
    <ModuleNotFound>ModuleNotFound({0}, {1})</ModuleNotFound>
    <ExternalModuleError>ExternalModuleError({0}, {1})</ExternalModuleError>
    <RecursiveModuleReference>RecursiveModuleReference({0})</RecursiveModuleReference>
    <UnrecognizableGlobalPackageUse>UnrecognizableGlobalPackageUse</UnrecognizableGlobalPackageUse>
    <TypeNameNotFound>TypeNameNotFound({0})</TypeNameNotFound>
    <TypeArityMismatch>TypeArityMismatch({0}, {1})</TypeArityMismatch>
    <DuplicateFieldKey>DuplicateFieldKey({0}, {1})</DuplicateFieldKey>
    <RedeclarationOfSpecialGlobalVariable>RedeclarationOfSpecialGlobalVariable({0}, {1}, {2})</RedeclarationOfSpecialGlobalVariable>
    <RedeclarationOfBasicType>RedeclarationOfBasicType({0})</RedeclarationOfBasicType>
    <RedeclarationOfTypeVariable>RedeclarationOfTypeVariable({0}, {1})</RedeclarationOfTypeVariable>
    <UndeterminedGlobalVariableEnvironment>UndeterminedGlobalVariableEnvironment({0}, {1})</UndeterminedGlobalVariableEnvironment>
    <GlobalNameCollision>GlobalNameCollision({0}, {1}, {2}, {3})</GlobalNameCollision>
    <GlobalTypeCollision>GlobalTypeCollision({0}, {1}, {2}, {3})</GlobalTypeCollision>
    <UnrecognizedFeatureName>UnrecognizedFeatureName({0})</UnrecognizedFeatureName>
    <UnexpectedMultiType>UnexpectedMultiType</UnexpectedMultiType>
    <RequireMultiType>RequireMultiType</RequireMultiType>
    <DuplicateTag>DuplicateTag({0}, {1})</DuplicateTag>
    <FieldParentTagNotFound>FieldParentTagNotFound</FieldParentTagNotFound>
    <GenericTagParentSyntaxNotFound>GenericTagParentSyntaxNotFound</GenericTagParentSyntaxNotFound>
    <TypeTagParentSyntaxNotFound>TypeTagParentSyntaxNotFound</TypeTagParentSyntaxNotFound>
    <Info>Info</Info>
    <Warning>Warning</Warning>
    <Error>Error</Error>
    <NoFeatures>NoFeatures</NoFeatures>
    <GlobalRequire>GlobalRequire</GlobalRequire>
    <GlobalPackage>GlobalPackage</GlobalPackage>
    <GenericTypeParameters>GenericTypeParameters</GenericTypeParameters>
    <GenericTypeSubstitute>GenericTypeSubstitute({0}, {1})</GenericTypeSubstitute>
    <OtherFieldLocation>OtherFieldLocation</OtherFieldLocation>
    <OtherTagLocation>OtherTagLocation</OtherTagLocation>
    <Type1Source>Type1Source</Type1Source>
    <Type2Source>Type2Source</Type2Source>
    <Constraints1Source>Constraints1Source</Constraints1Source>
    <Constraints2Source>Constraints2Source</Constraints2Source>
    <RequiresTypeSource>RequiresTypeSource</RequiresTypeSource>
    <ActualTypeSource>ActualTypeSource</ActualTypeSource>
    <ConstraintsSource>ConstraintsSource</ConstraintsSource>
    <TypeSource>TypeSource</TypeSource>
  </diagnostic-messages>
  <log-messages>
    <LoadResourceFrom>LoadResourceFrom({0})</LoadResourceFrom>
    <ServerStarting>ServerStarting</ServerStarting>
    <ServerTerminatedNormally>ServerTerminatedNormally</ServerTerminatedNormally>
    <RequestCanceled>RequestCanceled({0})</RequestCanceled>
    <MessageParseError>MessageParseError({0})</MessageParseError>
    <ReceivedExitNotification>ReceivedExitNotification</ReceivedExitNotification>
    <MessageReceived>MessageReceived({0})</MessageReceived>
    <UnknownRequest>UnknownRequest({0}, {1}, {2})</UnknownRequest>
    <UnknownNotification>UnknownNotification({0}, {1})</UnknownNotification>
    <InvalidMessageFormat>InvalidMessageFormat({0})</InvalidMessageFormat>
    <ErrorResponseReceived>ErrorResponseReceived({0})</ErrorResponseReceived>
    <ResponseHandlerNotFound>ResponseHandlerNotFound({0}, {1})</ResponseHandlerNotFound>
    <ResourceValidationError>ResourceValidationError({0})</ResourceValidationError>
    <MessageSending>MessageSending({0})</MessageSending>
    <BeginCheck>BeginCheck({0})</BeginCheck>
    <EndCheck>EndCheck({0}, {1})</EndCheck>
    <UnopenedFileDiagnosticsIsNotPublished>UnopenedFileDiagnosticsIsNotPublished({0})</UnopenedFileDiagnosticsIsNotPublished>
    <FileChanged>FileChanged({0}, {1})</FileChanged>
  </log-messages>
</resources>
